site_name: Serversify
site_url: https://help.serversify.net

theme:
  name: material
  
  static_templates:
    - 404.html
    - CNAME


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
